spring:
  application:
    name: eurekaserver

  security:
    user:
      name: mscredito-eureka-user
      password: abcd@1234

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false